
package com.mycompany.mysimplelogic.gui;

import java.awt.*;
/**
 *
 * @author Antoni Jan Nowaczyk
 */
public class CircuitPanel extends javax.swing.JPanel {
    
    private final int WIDTH = 200;
    private final int HEIGHT = 200;
    
    private int gridsize = 20;
    
    /**
     * Creates new form circuitPanel
     */
    public CircuitPanel() {
        this.setSize(WIDTH, HEIGHT);
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        int nrOfCells = WIDTH / gridsize;

        g.setColor(Color.GRAY);
        for (int i = 0; i < nrOfCells; i++) {
            for (int j = 0; j < nrOfCells; j++) {
                g.drawRect(i * gridsize, j * gridsize, gridsize, gridsize);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
