
package com.mycompany.mysimplelogic.gui;

import java.awt.*;
/**
 *
 * @author Antoni Jan Nowaczyk
 */
public class CircuitPanel extends javax.swing.JPanel {
    
    private final int WIDTH = 400;
    private final int HEIGHT = 300;
    
    private int gridsize = 25;
    private int offsetX = 0;
    private int offsetY = 0;
    
    private int highlightX = WIDTH / 2;
    private int highlightY = HEIGHT / 2;
    /**
     * Creates new form circuitPanel
     */
    public CircuitPanel() {
        this.setSize(WIDTH, HEIGHT);
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        int nrOfRows = WIDTH / gridsize;
        int nrOfCols = HEIGHT / gridsize;

        g.setColor(Color.GRAY);
        for (int i = -1; i < nrOfRows + 1; i++) {
            for (int j = -1; j < nrOfCols + 1; j++) {
                g.drawRect(i * gridsize + offsetX, j * gridsize + offsetY, gridsize, gridsize);
            }
        }
        g.setColor(Color.RED);
        g.fillOval(highlightX - 5, highlightY - 5, 10, 10);
    }
    
    public void moveHighlight(int x, int y) {
        highlightX += (x * gridsize);
        highlightY += (y * gridsize);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
