
package com.mycompany.mysimplelogic.gui;

import com.mycompany.mysimplelogic.circuitElements.AbstractGate;
import com.mycompany.mysimplelogic.circuitElements.AndGate;
import com.mycompany.mysimplelogic.circuitElements.Location;
import java.awt.*;
import java.util.ArrayList;
/**
 *
 * @author Antoni Jan Nowaczyk
 */
public class CircuitPanel extends javax.swing.JPanel {
    
    private final int WIDTH = 400;
    private final int HEIGHT = 300;
    
    private int gridsize = 25;
    private int offsetX = 0;
    private int offsetY = 0;
    
    private int nrOfRows = WIDTH / gridsize;
    private int nrOfCols = HEIGHT / gridsize;
    
    private int highlightX = nrOfRows / 2;
    private int highlightY = nrOfCols / 2;
    
    private ArrayList<AbstractGate> gates;
    private ArrayList<ArrayList<Location>> grid;
    private ArrayList<Location> powered;
    
    /**
     * Creates new form circuitPanel
     */
    public CircuitPanel() {
        grid = new ArrayList<>();
        gates = new ArrayList<>();
        powered = new ArrayList<>();
        
        for (int i = 0; i < nrOfRows; i++) {
            ArrayList<Location> row = new ArrayList<>();
            for (int j = 0; j < nrOfCols; j++) {
                row.add(new Location(i, j));
            }
            grid.add(row);
        }
        
        this.setSize(WIDTH, HEIGHT);
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        //Paint grid.
        g.setColor(Color.GRAY);
        for (ArrayList<Location> row : grid) {
            for (Location loc : row) {
                g.drawRect(loc.get_row() * gridsize, loc.get_col() * gridsize, gridsize, gridsize);
            }
        }
        //Paint gates.
        g.setColor(Color.BLUE);
        for (AbstractGate gate : gates) {
            g.fillRect(gate.getLocation().get_row() * gridsize, gate.getLocation().get_col() * gridsize, gridsize, 2 * gridsize);
            g.fillOval(gate.getLocation().get_row() * gridsize - 5, (gate.getLocation().get_col() + 1) * gridsize - 5, 10, 10);
        }
        //Paint powered cells.
        for (Location loc : powered) {
            g.setColor(Color.YELLOW);
            g.fillOval(loc.get_row() * gridsize - 5, loc.get_col() * gridsize - 5, 10, 10);
        }
        //Paint highlight.
        g.setColor(Color.RED);
        g.fillOval(highlightX * gridsize - 5, highlightY * gridsize - 5, 10, 10);
    }
    
    public void moveHighlight(int x, int y) {
        highlightX += x;
        highlightY += y;
    }
    
    public void addGate(String type) {
        AbstractGate newGate;
        Location st = grid.get(highlightX).get(highlightY);
        Location nd =  grid.get(highlightX).get(highlightY + 2);
        Location out = grid.get(highlightX + 1).get(highlightY + 1);
        switch (type) {
            case "AND" -> newGate = new AndGate(st, nd, out);
            default -> { newGate = null; }
        }
        gates.add(newGate);
    }
    
    public void powerUp() {
        grid.get(highlightX).get(highlightY).set();
        powered.add(grid.get(highlightX).get(highlightY));
    }
    
    public void rebool() {
        for (AbstractGate gate : gates) {
            gate.eval();
            if (gate.Output().get()){
                powered.add(gate.Output());
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
